spring.application.name=project
spring.datasource.url=jdbc:mysql://localhost:3306/HR
spring.datasource.username=root
spring.datasource.password=YUTA@^!)(%

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true